### ISSUE TITLE
[Bug] Cant install dependencies

### ISSUE THREAD

**Issue by benji56** [creativetimofficial/ct-muse-vue-ant-design-dashboard-pro#1]
### Version
1.0.0
### Reproduction link
http://cant.send.this.com
### Operating System
windows 10
### Device
Visual studio code bash terminal
### Browser & Version
-
### Steps to reproduce
-read the documentatnion
-unzip the project
-run npm install
-Error:

$ npm install
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated html-webpack-plugin@3.2.0: 3.x is no longer supported
npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm WARN deprecated core-js@2.6.12: core-js@<3.4 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm ERR! code 1
npm ERR! path C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\node-sass
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node scripts/build.js
npm ERR! Building: C:\Program Files\nodejs\node.exe C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp verb cli [
npm ERR! gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
npm ERR! gyp verb cli   'C:\\Users\\Solar_Storm_3\\Documents\\PROJECTNAME website\\node_modules\\node-gyp\\bin\\node-gyp.js',
npm ERR! gyp verb cli   'rebuild',
npm ERR! gyp verb cli   '--verbose',
npm ERR! gyp verb cli   '--libsass_ext=',
npm ERR! gyp verb cli   '--libsass_cflags=',
npm ERR! gyp verb cli   '--libsass_ldflags=',
npm ERR! gyp verb cli   '--libsass_library='
npm ERR! gyp verb cli ]
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@16.14.0 | win32 | x64
npm ERR! gyp verb command rebuild []
npm ERR! gyp verb command clean []
npm ERR! gyp verb clean removing "build" directory
npm ERR! gyp verb command configure []
npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
npm ERR! gyp verb `which` failed Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21)
npm ERR! gyp verb `which` failed  python2 Error: not found: python2
npm ERR! gyp verb `which` failed     at getNotFoundError (C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\which\which.js:13:12)
npm ERR! gyp verb `which` failed     at F (C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\which\which.js:68:19)
npm ERR! gyp verb `which` failed     at E (C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\which\which.js:80:29)
npm ERR! gyp verb `which` failed     at C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\which\which.js:89:16
npm ERR! gyp verb `which` failed     at C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\isexe\index.js:42:5
npm ERR! gyp verb `which` failed     at C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\isexe\windows.js:36:5
npm ERR! gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:198:21) {
npm ERR! gyp verb `which` failed   code: 'ENOENT'
npm ERR! gyp verb `which` failed }
npm ERR! gyp verb check python checking for Python executable "python" in the PATH
npm ERR! gyp verb `which` succeeded python C:\Python310\python.EXE
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Command failed: C:\Python310\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
npm ERR! gyp ERR! stack SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
npm ERR! gyp ERR! stack
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:399:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:520:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1092:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.19042
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Solar_Storm_3\\Documents\\PROJECTNAME website\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
npm ERR! gyp ERR! cwd C:\Users\Solar_Storm_3\Documents\PROJECTNAME website\node_modules\node-sass
npm ERR! gyp ERR! node -v v16.14.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
npm ERR! Build failed with error code: 1

### What is expected?
install dependencies
### What is actually happening?
-

---

**Comment by dragosct** [comment]
Hi, @benji56! Thanks for using our products. Please make the next steps: 

1. Uninstall node-sass using the following command: `npm un node-sass`
2. Install sass using the following command: `npm i sass`
3. Then run `npm install`

Regards,
Dragos

**Comment by jaymegordo** [comment]
@dragoshict  I'm having the same issue but those steps didn't resolve it for me. The issue really looks like its expecting to run that file with python2.

node -v 18.0.0
M1 MacBook Pro Monterey

**Comment by hungdv98** [comment]
> @dragoshict I'm having the same issue but those steps didn't resolve it for me. The issue really looks like its expecting to run that file with python2.
> 
> node -v 18.0.0 M1 MacBook Pro Monterey

maybe you should downgrade your node version, I can build and run with node v14.21.3
